from OpenAIAgent import OpenAIAgent
from tools import *

class ToolExecutionResult:
    def __init__(self, success: bool, content: tuple[dict, dict]|list[dict]):
        self.success = success
        self.content = content

class ExecuterAgent(OpenAIAgent):
    def __init__(
        self,
        system_prompt: str,
        prompt_template: str,
        user_input_param_name: str = "query",
    ):
        super().__init__(system_prompt, prompt_template, user_input_param_name)
    
    def request_payload(self, message: str, stream: bool = False):
        messages = self.history[:-1] + [OpenAIAgent.user_snapshot(content=message)]
        tools = get_all_tools_schemas()
        return {
            "model": self.model,
            "input": messages,
            'tools': tools, 
            "stream": stream
        }

    def request(self, payload: dict):
        return self.client.responses.create(**payload)
    
    def execute(self, query):
        payload = self.request_payload(query,)
        response = self.request(payload)
        tool_calls = ExecuterAgent.extract_tool_calls(response)
        if not tool_calls:
            response_text = ExecuterAgent.get_response_text(response)
            return response_text
        
        tools_lookup = {
            tool: get_tool_function(tool)
            for tool in TOOLS_REGISTRY
        }
        snapshots = self.execute_tools(query, tool_calls, tools_lookup)
        return self.format_tools_response(snapshots, tools=get_all_tools_schemas())
    
    @staticmethod
    def extract_tool_calls(response):
        tool_calls = [item for item in response.output if item.type == "function_call"]
        return tool_calls

    def execute_tools(self, user_query, tool_calls, tools_lookup: dict):
        snapshots = self.history + [OpenAIAgent.user_snapshot(user_query)]
        snapshots += [tool.model_dump() for tool in tool_calls]
        for tool_call in tool_calls:
            name = tool_call.name
            tool = tools_lookup[name]

            try:
                args = json.loads(tool_call.arguments)
            except Exception as exception:
                print('execute_tool_ERROR', f'[{name=}], [{type(exception).__name__=}], [{str(exception)=}]')
        
            tool_resp = tool(**args)
            tool_resp = json.dumps(tool_resp, ensure_ascii=False)
            snapshots.append({
                "type": "function_call_output",
                "call_id": tool_call.call_id,
                "output": tool_resp
            })

        return snapshots
            
    @staticmethod
    def get_response_text(response):
        return '\n'.join([
            '\n'.join([
                content.text for content in item.content
            ])
            for item in response.output
        ])

    def format_tools_response_payload(self, snapshots, tools):
        payload = {
            'model': self.model,
            'input': snapshots,
            'tools': tools,
            'instructions': "Respond only with the output generated by a tool.",
            'stream': False
        }
        return payload

    def nonstream_format_tools_response(self, response):
        text_response = response.output_text
        return text_response
    
    def stream_format_tools_response(self, response):
        full_text = ''
        for event in response:
            if event.type == 'response.output_text.delta':
                txt = event.delta
                full_text += txt
                # self.partial_memorize(txt)
                yield txt

    def format_tools_response(self, snapshots, tools):
        payload = self.format_tools_response_payload(snapshots, tools)
        response = self.request(payload)
        return self.nonstream_format_tools_response(response)
        # if not self.stream:
        #     return self.nonstream_format_tools_response(response)
        # return self.stream_format_tools_response(response)